### ISSUE TITLE
Mobile Phone Video on Homepage

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#116]
![image](https://user-images.githubusercontent.com/79876365/123303691-ae305580-d4e3-11eb-8c13-03e0e874882b.png)

**Comment by arthurgloer** [comment]
I can't seem to replicate this one. Can you give me all the details you can so that I can see it?

**Comment by baudoinalkali** [comment]
I can't replicate it in the browser, this screenshot is on my iPhone.

**Comment by arthurgloer** [comment]
Got a hold of an iPhone, I can see it now.

**Comment by arthurgloer** [comment]
I've figured it out. I ran out of time to work today though, so it still needs to be centered. If you're in a big rush, you can pretty easily do that. I believe tailwind has a class text-center that you can put on the parent container.
https://chattr-caz18knz2-nick-alkalidesign.vercel.app/

**Comment by arthurgloer** [comment]
You can see on iPhone the phone looks good though.

**Comment by arthurgloer** [comment]
Fixed!
