### ISSUE TITLE
Pricing Feature/ToolTip Component

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#12]
Please create the component for this section (![image](https://user-images.githubusercontent.com/79876365/117924471-69e25080-b2bb-11eb-9dd3-17dc04769e5c.png)). The content isn't final, what is would be the headings such as Jobs Management, AI Hiring Assistant, Interview Booking, etc. I'm thinking it would be best to set up arrays for them and we can set up the data maps, then just fill in the information afterwards. I attached the images backgrounds. Here is a breakdown on the styling:

Titles (Jobs Management, AI Hiring Assistant): text-xl font-avantbold
Features (Branded Job Portal, Free Job Board Postings Distribution):  font-proximasemi text-xl
Tool tip text: font-proximasemi text-md

Here are the .svgs:

https://drive.google.com/drive/folders/1WUUiYOWUs6K8tpmQtZfSzO1C8zUMaW0N?usp=sharing

**Comment by ogdenstudios** [comment]
Got it. Work is a little hectic today, so I should be able to finish this up by late tomorrow evening worst case.

**Comment by baudoinalkali** [comment]
They said to continue with the tooltip.

**Comment by ogdenstudios** [comment]
@baudoinalkali - the Google drive folder you sent along doesn't have the tooltip background. You have a file with that name, but it's just the yellow title background. Can you send me the tooltip bg when you get a chance, please?

**Comment by baudoinalkali** [comment]
Sorry about that, here is the correct SVG: https://drive.google.com/file/d/1WCNXz5rxsVEY9bEjbLs_A461YPaIk4nO/view?usp=sharing
