### ISSUE TITLE
Product Phone Issue

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#120]
If you checkout the branch optimizationtests, there is an odd issue on the product page where the smile location is being screwed up. The only difference (I've tested) which seems to be causing this is:

purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],

in the tailwind config file. This is rather important to have as it purges all unused tailwind CSS and speeds things up quite a bit. Can you look into fixing this?

![image](https://user-images.githubusercontent.com/79876365/123352319-a9d85c80-d524-11eb-833c-bb3aaa8184d1.png)

**Comment by arthurgloer** [comment]
So this is actually a very simple bug! We've got to add to change that line:
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}', './utilities/**/*.{js,ts,tsx}'],

**Comment by arthurgloer** [comment]
Some of the classes you need are in the utilities folder. Not exactly sure how to mess with that branch, because you're many commits behind and ahead of main, so I don't want to get us into a monster commit mess. Since you were working on it, I bet you know the best way to make the change?
