### ISSUE TITLE
Updated Forumla

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#14]
Hopefully this makes sense. We are getting rid of "new number of days to fill an open job"

We will have How many locations do you have, How many hours do you spend per week reading resumes and calling applicants, and How much do you pay your hiring managers per hour

The if they have 1-5 locations it's $97 per location, 6-10 is $87, 11-20 is $77, and 21+ should say "Contact Us For Special Pricing"(or whatever we change it to later on).

If I have 4 locations, spend 10 hours per week, and page my manager $25/hr the equation would be (25/hr6hours4locations52weeks)-(4locations*97*12months)

So the formula itself would be (Manager Salary * Recruiting Hours * # of Locations * 52 weeks) - (4 locations * Location Price based on volume)

The solution to this equation would be what's under "Annual operational savings with Chattr"

There is only one extra conditional logic part and that is to do with the locations. They work on pricing tiers, so here is the list:

1-5 Locations: $97
6-10 Locations: $87
11-20 Locations: $77
21+ Locations: Custom (Instead of number say "Contact Us For Special Pricing") verbiage will probably change.

**EDIT** There is a slight chance we still include "How many days does it take to fill an open role", that is still being decided upon. It would have no impact to the above formula as the result is actually the same no matter what their input is as they have an exact average their customers expect, so they felt it would be redundant, but just wanted to bring that up in case it changes your approach if they change their minds.

**Comment by ogdenstudios** [comment]
Awesome - I'll get started later tonight or sometime tomorrow. Shouldn't take too long.

**Comment by baudoinalkali** [comment]
Sounds good. I should have some more issues shortly. This client is a big fan of hand drawn mock-ups, I don't want to put your through that so I'm roughly mocking them up on Figma lol.

**Comment by ogdenstudios** [comment]
Haha thanks I appreciate that!

**Comment by baudoinalkali** [comment]
Almost, I believe you left out the fixed multiplier of 12 for the cost of the service, which is then substracted from the first equation. I got your number by doing (number of locations*$97), it should be (number of location * $97 * 12). Here are what the results should be for the scenarios you provided:

![image](https://user-images.githubusercontent.com/79876365/118334939-2ca4db00-b4d4-11eb-85ac-1849bff11829.png)

**Comment by ogdenstudios** [comment]
I think I got it, then. [Will you do a final check on the tests I wrote, please](https://github.com/baudoinalkali/chattr/blob/0ba9389628e24462dfb57e0cf6a6a1b4a97a5b9c/spec/calculator.test.js#L13)?

Another question: if the result has a decimal, do we want to round it in any way? I could round to the nearest whole number, I could take the floor (so round to the lowest whole number it's in between), or I could take the ceiling (round to the highest whole number it's in between), or I could just round to two decimal places. 

I think once we answer that, we'll be in good shape here.

**Comment by baudoinalkali** [comment]
Let's do neared whole number. 

Maybe I'm not looking at it right, but it seems the to be numbers are different than the results above.

**Comment by ogdenstudios** [comment]
Yes, sorry maybe I misunderstood. The formulas you posted as a screenshot excluded the 12 month multiplier for the second two scenarios. I added it and that's what's in the specs now. 

Are the values in your screenshot the correct ones? If so, I'll remove the multiplier. 

If that isn't quite making sense, maybe we find 10-15 minutes this weekend to talk it out over video?

**Comment by baudoinalkali** [comment]
I am so glad you caught that lol, I apparently sent the screenshot before I added the 12 multiplier. How you have it is perfect!

**Comment by ogdenstudios** [comment]
Haha awesome. This stuff can get fiddly since precision matters so much. I'm wrapping up for the night but I'll add the rounding function and a few additional tests early tomorrow and we can wrap this up.

**Comment by ogdenstudios** [comment]
Pulling [your comments from the PR](https://github.com/baudoinalkali/chattr/pull/16#issuecomment-841710346) here to keep it all together: 

> Looks good, question about animations you brought up earlier. Can we have the numbers animate instead of instantly appearing? Also can we add a $ to the front?

For styling can we change do the following:

"annual operational savings" : text-2xl font-avantbold color-chablack-300
"annual $ total" " text-4xl font-avantbold color-chagreen-300
"estimated savings" same as "number of locations"

**Comment by ogdenstudios** [comment]
@baudoinalkali - I can do all that. I'm sure we'll want to go back and forth on the actual animation style, but I can do the other stuff and get us started with a baseline animation to begin.
