### ISSUE TITLE
Pricing FAQ Dropdown

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#23]
Let's go ahead and build out the FAQ section that is shown here in the pricing mockup (
![image](https://user-images.githubusercontent.com/79876365/118411393-e6798400-b659-11eb-9140-aa1aa29478a5.png)). To the best of my knowledge this is not utilized anywhere else, but we might as well make it a component because I can imagine them reusing it. Let's set up a content file that stores the headline, body, and image. 

Let's not worry about mocking up that image for now as those are subject to change, just grab a random image we already have (like one of the phones used on the product page).

Styles:

FAQ headline already done
Item headline: text-chablack-300 text-2xl font-avantbold
Item body: text-chablack-300 text-lg font-proximasemi
Content getting revealed speed- duration-500

**Comment by baudoinalkali** [comment]
@ogdenstudios Was thinking about using https://headlessui.dev/react/disclosure for the FAQ dropdown as well as desktop dropdown (Features will be a dropdown) as well as mobile dropdown. Any problem potential issues that would lead you to recommend against that?

**Comment by ogdenstudios** [comment]
I think that's a great option!
