### ISSUE TITLE
Animation MVP

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#24]
As discussed let's have the smile appear in and then proceed to move in its current fashion.

**Comment by baudoinalkali** [comment]
Question, they like the appearing animation a lot, are there any negative implications to reusing just that for all the orange banner text? Not sure if I mentioned this before, but that tail on the top right is an SVG so the plan was to have that animated as well, so the tail and the text would pop up together, then the tail would move up and down. (pic attached for reference)
![image](https://user-images.githubusercontent.com/79876365/118838034-f62bdf00-b88a-11eb-9943-1d47e2cf19cc.png)

**Comment by baudoinalkali** [comment]
@ogdenstudios Let's go ahead and add the appear animation to the text and appear and go up and down animation to the yellow tail. Let's hold off on applying the animation everywhere, just want make sure they're all good with the animation after taking some time.

**Comment by ogdenstudios** [comment]
Awesome. I'll find some time for that between today and tomorrow and push it to this MR. That way we can use this deploy preview to show how it looks with the text as well.

**Comment by baudoinalkali** [comment]
@ogdenstudios Okay after some convincing, please move forward with applying the appear animation to all headlines (I have a component set up for them called orangeBanner which should hopefully make that easier), up and down animation to the yellow tail, and appear and up and down animation to all smile SVGs.

**Comment by ogdenstudios** [comment]
Sounds good! I'll work on this today as well.

**Comment by baudoinalkali** [comment]
Great, I'm going to work on responsive parts this weekend. I'm hoping to have a first draft to present Monday. No problem if certain parts are missing, just wanted to keep you apprised when you see me pushing stuff.
