### ISSUE TITLE
About Values Shape Insert

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#28]
Please replace the blurb for the "our position" portions with the attached one:

https://drive.google.com/file/d/1Dx3K5xVnIJ67D-d5Umbb1VK7adnq1fxN/view?usp=sharing

Question regarding the border that overlaps with. I used CSS for the shape, is that the best way to do it? Is that what you did for the pricing page and the about illustration below?

**Comment by ogdenstudios** [comment]
Awesome, I'll try to take a look at this sometime tomorrow. 

Yeah I would probably use this as a CSS background specifically.
