### ISSUE TITLE
Pricing Toggle Functionality

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#4]
Please set up the pricing toggle functionality 
![image](https://user-images.githubusercontent.com/79876365/116952504-6bbf6a80-ac50-11eb-80ac-b407caf6d7ce.png). I have created one price container (feel free to duplicate it) with most of the styling. The only changes resulting from the toggle will be the dollar figure. Just want to get the functionality there while I wait on the design sign-off.

**Comment by baudoinalkali** [comment]
@ogdenstudios Realized I didn't tag you on this.

**Comment by ogdenstudios** [comment]
Got it! Thanks. 

You can also add me as an assignee in the top right for future issues. I'll get started. Should be wrapped tonight or tomorrow!

**Comment by baudoinalkali** [comment]
Ahh good to know.
