### ISSUE TITLE
Phone/Smile Animation Idea

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#54]
@ogdenstudios Let me know your thoughts regarding the below video:

https://www.loom.com/share/72710b8ea4ab4a4d9266e000e7964762?sharedAppSource=personal_library

**Comment by ogdenstudios** [comment]
Hey @baudoinalkali - we can do this. It's not terribly complicated or time consuming. Maybe a couple of hours, tops. 

The bigger concern I have is that the animation might just be too much if they're applying it to all those graphics, especially on the product page where we have half a dozen or so of them. 

But I think it's reasonable to take a couple hours to demo it for them. We can do a deploy preview branch and just apply it everywhere to see if it feels "too much" in context. If applying it to all of them feels too heavy handed, we can at consider applying it partially throughout, or scrap it. 

So yeah, if it you think like 3-5 hours is worth it (probably like, 2-3 hours for an initial build, and then another few for revisions), then I'm happy to put something together.

**Comment by baudoinalkali** [comment]
Sounds good, let's go ahead and get the others taken care of first. I'll try to gauge their interest in the animation.

**Comment by ogdenstudios** [comment]
Got it. I'll prioritize the other issues.
