### ISSUE TITLE
Homepage Illustration Animation

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#56]
Can we add the appear and float up and down animation to the containers on the illustration section (image for reference attached)?
![image](https://user-images.githubusercontent.com/79876365/120422240-75122480-c32d-11eb-98ec-ff435332b54c.png)

**Comment by ogdenstudios** [comment]
@baudoinalkali - sure thing. We're going to do some hiking today, but I can get to this later tonight or sometime tomorrow.
