### ISSUE TITLE
Animate Yellow Footer Branding Element

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#57]
They decided to go ahead and have that animated. I attached a screenshot of the specific element: 
![image](https://user-images.githubusercontent.com/79876365/120422293-9246f300-c32d-11eb-8bd3-ab12acd69ce9.png)

**Comment by ogdenstudios** [comment]
@baudoinalkali - works for me. We're going to do some hiking today, but I can get to this later tonight or sometime tomorrow.
