### ISSUE TITLE
Blurb Fix Homepage

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#7]
Can you refine this? Having to focus on some other things atm. The ideal look is: 
![image](https://user-images.githubusercontent.com/79876365/117225575-3fcef100-add8-11eb-910e-ccd7f64570eb.png)
How it is currently:
![image](https://user-images.githubusercontent.com/79876365/117225589-49f0ef80-add8-11eb-80af-5e04f396795a.png)

I'm working on getting the correct headshot, but let's just ignore the huge chunk in the image.

**Comment by ogdenstudios** [comment]
Yeah, I should be able to get to this tomorrow. I got my second COVID shot today, so I might end up bout of commission. I'll let you know if it'll take longer. 

Do you have those Xd files? This one would be a lot easier to do with the detailed specs. If not, I can still get us closer. Thanks!

**Comment by baudoinalkali** [comment]
This isn't in XD unfortunately. You can reference it on their current site https://chattr.ai, but it's all an image so now sure how helpful that is.

**Comment by ogdenstudios** [comment]
All good! I'll get it as close as we can, although we still may not get pixel perfect without those specs.
