### ISSUE TITLE
Animation Overlapping Issue on Homepage DualCTA Component and Video

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#78]
@arthurgloer Here is a video showcasing the issue. Code I referenced is in index.js, the CTAs are in a component called DualCTAs.js and video is PopupVideo.js component.

https://www.loom.com/share/8dc9b90420114a55a3ac835064a9a2b0

**Comment by arthurgloer** [comment]
1 hour. Done. Checkout branch overlayFix.
