### ISSUE TITLE
Add Thank You Page/Confetti Animation

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#79]
@arthurgloer Please find the video explaining this issue attached. At the end I said I would follow up with the images, forgot I already had them, I figured a Google Drive link might be easier, that way you can set it up however you'd like: 

Confetti Smiles for animation: https://drive.google.com/drive/folders/13x0X5oqAqWGNgk5lkw6EaQyP0PQU7uiu?usp=sharing

Video: https://www.loom.com/share/f99d564e08dc442195e96c84b85c15eb

Notes shown in video:

Use this javascript package: https://www.npmjs.com/package/confetti-js

Use these config settings for the package: confettiSettings = { target: 'p5', props: [{ "type": "svg", "src": blueImage, "size": 20 }, { "type": "svg", "src": greenImage, "size": 20 }, { "type": "svg", "src": pinkImage, "size": 20 }, { "type": "svg", "src": yellowImage, "size": 20 }, { "type": "svg", "src": purpleImage, "size": 20 }], rotate: true, clock: 20, max: 100, respawn: false, start_from_edge: true};

He can reference this too:
 let confettiSettings;
    let confetti;    useEffect(() => {
        setTimeout(() => {
            makeConfetti();
        }, 1000);
    }, [])    const makeConfetti = () => {
        confettiSettings = { target: 'p5', props: [{ "type": "svg", "src": blue, "size": 20 }, { "type": "svg", "src": green, "size": 20 }, { "type": "svg", "src": pink, "size": 20 }, { "type": "svg", "src": yellow, "size": 20 }, { "type": "svg", "src": purple, "size": 20 }], rotate: true, clock: 20, max: 100, respawn: false, start_from_edge: true};
        confetti = new ConfettiGenerator(confettiSettings);
        confetti.render();
    }

**Comment by arthurgloer** [comment]
I've linked the thank you page. I think you wanted to customize the thank you page, so not going to do a pull request.

**Comment by baudoinalkali** [comment]
Not sure if this is a standard practice, but I usually just do a PR for anything that is ready for review because Vercel will automatically make a preview for the PR.

**Comment by baudoinalkali** [comment]
Looks good, I would say this one is good!
