### ISSUE TITLE
Homepage Testimonial Slider Dot Size

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#92]
Here is the video for this issue: https://www.loom.com/share/eccc2136c70944a286472cb4df0db2be

**Comment by arthurgloer** [comment]
I actually did it with just this block of css:
.slick-dots li {
    zoom: 2;
}

**Comment by arthurgloer** [comment]
If you want, you can just tweak that "2" to whatever you want, because obviously half would make it 1, and it'd be just as it was before.

**Comment by baudoinalkali** [comment]
Would the clicking issue still be there if we set it to 1?
