### ISSUE TITLE
Homepage Phone Video

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#93]
Here is the video for this issue: https://www.loom.com/share/429d1c717ae54a83a583df2e6094e656

**Comment by arthurgloer** [comment]
Ok, wow, so this really stumped me for a while. But the video has a black background, because the video couldn't have a transparent background, it went ahead and converted all transparencies to black. You might be better off just making that into a gif or saving the video again with a white background and cropping to the phone as close as possible.

**Comment by arthurgloer** [comment]
On another note, I don't see the smile under that video, was it removed?

**Comment by baudoinalkali** [comment]
@arthurgloer Are you sure the video background isn't transparent? How is it transparent before play is hit? There is no thumbnail assigned, it's pulling that from the video. From my perspective it seems like the background is being applied once play is hit, so there must be a way to disable it?

**Comment by arthurgloer** [comment]
This is the thumbnail that it's using for before play is hit: https://i.vimeocdn.com/video/1162273107?mw=500&mh=1019

**Comment by arthurgloer** [comment]
If you go to the page:
https://player.vimeo.com/video/562277627?speed=0&controls=0&autoplay=1&loop=1&app_id=122963?background=1&?muted=1

**Comment by arthurgloer** [comment]
Take a look under div with class: vp-preview, it's using the thumbnail image I've referenced above.

**Comment by baudoinalkali** [comment]
@arthurgloer I'm told it's a transparent video, so perhaps Vimeo is screwing something up? Can we try hosting it on the site itself? Here is a link to the video: https://drive.google.com/file/d/11lfqnisKVDZ4TmmOjlqoTyPYrVk613jr/view?usp=sharing

**Comment by arthurgloer** [comment]
Yes, from your link, I can see that it actually is a transparent video. Unfortunately, the only way that you can have a transparent video, that I know of is by using .mov, which they are using. Vimeo and any other service would transform that to probably .mp4. I did find this here though, that may solve our problems: http://transparentplayer.com/

**Comment by baudoinalkali** [comment]
@arthurgloer Sorry didn't see the reply. Would we be able to serve a .mov if we hosted it on the site itself? Would you be able to try integrating that solution if the previous possibility isn't possible? Also this is an option (if you think it would be easier or more straightforward) I have an .mp4 of just the screen, we could perhaps overlay the phone on top of it?

**Comment by arthurgloer** [comment]
So yes, we can serve a .mov on the site using this transparentplayer. The last option that you gave of using the mp4 of the screen and overlaying it on top of the phone is a brilliant one, and the one I think we should go with. If we go with the last option, I believe you can host the mp4 on vimeo as you were doing and it'd work out fine. I'd just need the phone image.

**Comment by arthurgloer** [comment]
Obviously the mp4 we'd be hosting would be the one of just the screen, as you'd mentioned.

**Comment by baudoinalkali** [comment]
Okay great, let me get that to you.

**Comment by baudoinalkali** [comment]
@arthurgloer 
Here is the video: https://drive.google.com/file/d/1RtyJf97SJcrHCCT2L09ht3s_oPyobgrm/view?usp=sharing
Here is the blank phone: https://drive.google.com/file/d/1xYUt5PakuAAET9avJsvJEl42GtkuTmdb/view?usp=sharing

If you could make this a component that would be ideal. On the products page in the future would all get replaced with what we're making now.

**Comment by arthurgloer** [comment]
That's a great idea, and exactly what I'll do!

**Comment by arthurgloer** [comment]
Would it be possible to upload that video to vimeo, so that I can have it pull from there?

**Comment by baudoinalkali** [comment]
@arthurgloer https://vimeo.com/563385036

**Comment by arthurgloer** [comment]
thanks

**Comment by arthurgloer** [comment]
Got it all working and fixed CSS issues for mobile too.

**Comment by baudoinalkali** [comment]
@arthurgloer Looks really good, it doesn't seem to be autoplaying on my end though.

**Comment by arthurgloer** [comment]
So that actually seems to be something on vimeo's end, because if you go straight to either one of these urls:
https://player.vimeo.com/video/562277627?speed=0&controls=0&autoplay=1&loop=1&app_id=122963?background=1&?muted=1
https://player.vimeo.com/video/563385036?speed=0&controls=0&autoplay=1&loop=1&app_id=122963?background=1&?muted=1

It won't autoplay...actually I remember that a lot of browsers won't allow autoplay in certain circumstances. Anyway, if we switch out controls=0 in those URLs for controls=1 they will autoplay.

**Comment by arthurgloer** [comment]
So that may just be a setting that we need to set up on Vimeo?

**Comment by arthurgloer** [comment]
actually it seems to be intermittent maybe? Really weird, but you can see the effect if you go straight to the URLs provided by vimeo, that sometimes they autostart and sometimes they don't.

**Comment by arthurgloer** [comment]
https://www.loom.com/share/087161db500f4b52b8f445e226c5ac6d
