### ISSUE TITLE
Homepage Product Section Button PopUp

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/chattr#98]
Overview video: https://www.loom.com/share/4abb8648af01464b86a1570eb275a757

**Comment by arthurgloer** [comment]
So what I'm going to do is I actually found a more eloquent way of resolving this issue, so I'm going to actually do that for each of these elements.

**Comment by baudoinalkali** [comment]
@arthurgloer Sounds good, please pull the main branch again as there have been some structure changes.

**Comment by arthurgloer** [comment]
Done and merged. We've got a new component ZoomInUp, which is a div wrapper element for "zoom-in-up" that won't give you the problems that you were experiencing.
